# Docker compose file for local development

version: "3.9"

services:
  notification_backend:
    build: .
    ports:
      - "8088:8000"
    env_file: .env

  notification_db:
    image: postgres:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5
    env_file:
      - .database.env
    volumes:
      - notification-postgres-data:/var/lib/postgresql/data

  notification-backend-migrate:
    build: .
    depends_on:
      notification_db:
        condition: service_healthy
    entrypoint: [ "alembic", "upgrade", "head" ]
    env_file: .env

  consumer:
    build: .
    depends_on: [ redis ]
    env_file: .consumer.env

  redis:
    image: redis:6

volumes:
  notification-postgres-data:
